id = "chawyehsu-vscode-icons"
name = "VSCode Icons"
version = "0.4.0"
schema_version = 1
authors = ["Chawye Hsu <su+zed@chawyehsu.com>"]
description = "vscode-icons theme for Zed"
repository = "https://github.com/chawyehsu/zed-vscode-icons-theme"
